### ISSUE TITLE
Combine EventIrcNoticed into EventIrcMessage using a boolean

### ISSUE THREAD

**Issue by 0x17de** [HarpoonOrg/Harpoon#2]
For cleanup remove EventIrcNoticed (including files, update CMakeLists.txt) and provide functionality via EventIrcMessage (adding a boolean if the event is a notice).
All occurrences where it is used should be fixed.

**Comment by hryniuk** [comment]
Thanks for merging my fixes :smiley:.

As I mentioned before, I'd like to take care of this issue. Could you assign me?
